import React, { createContext, useContext, useState, useEffect } from 'react';
import { Globe } from 'lucide-react';

// Define the available languages
const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' }
];

// Comprehensive translation dictionary
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.solutions': 'Solutions',
    'nav.method': 'The EA Method',
    'nav.why': 'Why EA Solutions?',
    'nav.contact': 'Contact',
    'nav.services': 'Services',
    'nav.mind': 'MIND',
    
    // Hero Section
    'hero.title': 'Your Business Has a Body. We Build Its Mind.',
    'hero.subtitle': 'We architect bespoke AI infrastructures that eradicate repetitive work, amplify human potential, and unlock unprecedented efficiency.',
    'cta.book': 'Book Your AI Strategy Call',
    'cta.explore': 'Explore Solutions',
    
    // Header
    'header.cta': 'Book AI Strategy Call',
    
    // MIND Product
    'mind.title': 'The Universal AI Solution',
    'mind.description': 'One intelligent system that adapts to every industry, every workflow, every challenge. MIND is not just AI – it\'s the evolution of how businesses think, learn, and grow.',
    'mind.tagline': 'One brain, infinite workflows.',
    'mind.trusted': 'Trusted by 4+ companies in Germany and 1 internationally',
    'mind.cta.start': 'Start Your AI Transformation',
    'mind.cta.demo': 'Watch Demo',
    'mind.cta.title': 'Ready to Unleash Your Organization\'s Mind?',
    'mind.cta.subtitle': 'Join the AI revolution. Transform your business. Unlock unlimited potential with MIND\'s universal intelligence.',
    'mind.cta.trial': 'Start Free Trial',
    'mind.cta.schedule': 'Schedule Demo',
    
    // MIND Features
    'mind.features.title': 'Why MIND Changes Everything',
    'mind.features.subtitle': 'Unlike traditional AI solutions that force you to adapt, MIND adapts to you with unprecedented intelligence and flexibility.',
    'mind.features.universal.title': 'Universal AI Intelligence',
    'mind.features.universal.desc': 'One AI system that adapts to any industry, any workflow, any challenge with unprecedented learning capabilities.',
    'mind.features.fast.title': 'Lightning-Fast Implementation',
    'mind.features.fast.desc': 'Deploy across your entire organization in weeks, not months, with zero disruption to existing workflows.',
    'mind.features.security.title': 'Enterprise-Grade Security',
    'mind.features.security.desc': 'Military-level encryption, zero-trust architecture, and compliance with all major international standards.',
    'mind.features.integration.title': 'Seamless Integration',
    'mind.features.integration.desc': 'Connects with 1000+ existing tools and platforms out of the box, with custom API development available.',
    
    // MIND Architecture
    'mind.architecture.title': 'Advanced AI Architecture',
    'mind.architecture.subtitle': 'Built on cutting-edge technology with enterprise-grade reliability and infinite scalability.',
    
    // MIND Industries
    'mind.industries.title': 'One Solution, Every Industry',
    'mind.industries.subtitle': 'MIND automatically configures itself for your specific industry needs with specialized modules and optimizations.',
    
    // MIND Pricing
    'mind.pricing.title': 'Transparent Pricing',
    'mind.pricing.subtitle': 'Choose the plan that fits your organization\'s size and ambitions. All plans include 30-day free trial.',
    'mind.pricing.pilot': 'Perfect for small teams testing AI transformation',
    'mind.pricing.growth': 'Comprehensive AI transformation for growing companies',
    'mind.pricing.scale': 'Advanced AI capabilities for scaling organizations',
    'mind.pricing.enterprise': 'Unlimited AI power with complete sovereignty',
    'mind.pricing.popular': 'Most Popular',
    'mind.pricing.contact': 'Contact Sales',
    'mind.pricing.trial': 'Start Free Trial',
    'mind.pricing.features': 'All plans include 30-day free trial • No setup fees • Cancel anytime',
    
    // MIND Testimonials
    'mind.testimonials.title': 'Trusted by Industry Leaders',
    'mind.testimonials.subtitle': 'Real results from real clients who chose MIND for their AI transformation.',
    
    // MIND ROI
    'mind.roi.title': 'Calculate Your ROI',
    'mind.roi.subtitle': 'See how much MIND can save your organization with our intelligent ROI calculator.',
    'mind.roi.employees': 'Number of Employees',
    'mind.roi.revenue': 'Annual Revenue (€)',
    'mind.roi.industry': 'Industry',
    'mind.roi.plan': 'Selected Plan',
    'mind.roi.monthly': 'Monthly Net Savings',
    'mind.roi.annual': 'Annual Net Savings',
    'mind.roi.payback': 'Payback',
    'mind.roi.benefits': 'Projected Benefits',
    'mind.roi.report': 'Get Detailed ROI Report',
    
    // Services
    'services.title': 'AI-Powered Websites & Apps',
    'services.subtitle': 'We build intelligent websites and applications with AI integration, smart automation, and modern design. 40-60% cost savings compared to big companies.',
    'services.tagline': 'Websites that think; apps that anticipate.',
    'services.development.tagline': 'Code once, let AI cut the cost in half.',
    'services.chatbot.tagline': 'Customer service that never sleeps (and never says, \'Please hold\').',
    'services.booking.tagline': 'Your calendar, already handled.',
    
    // Smart Home
    'smarthome.title': 'Smart Home Solutions',
    'smarthome.tagline': 'Turn four walls into a living, caring ally.',
    'smarthome.why.title': 'Why Home Automation?',
    'smarthome.why.subtitle': 'Because life\'s too short for busywork — let your home handle it.',
    'smarthome.errand.title': 'Errand-Free Living',
    'smarthome.errand.desc': 'Your Personal AI predicts when you\'re running low on groceries or household essentials, places the order, and schedules delivery while you focus on what matters.',
    'smarthome.booking.title': 'Instant Bookings & Plans',
    'smarthome.booking.desc': 'From concerts to flight check-ins, one voice command secures tickets, reserves tables, and updates your calendar — no apps, no queues, no stress.',
    'smarthome.climate.title': 'Perfect Climate, Always',
    'smarthome.climate.desc': 'Adaptive sensors learn your comfort patterns and the local weather, fine-tuning heating, cooling, and air-quality in real time. Save up to 40% on energy without lifting a finger.',
    'smarthome.security.title': 'Shield-Level Security & Fire Guard',
    'smarthome.security.desc': 'AI-driven cameras, smart locks, and smoke/CO detectors detect anomalies in milliseconds, trigger alerts, and can even call emergency services — whether you\'re downstairs or thousands of miles away.',
    'smarthome.care.title': 'Care Beyond Distance',
    'smarthome.care.desc': 'Discreet fall sensors, medication reminders, and two-way video check-ins keep older parents safe and connected. If something\'s wrong, you and emergency responders know immediately.',
    'smarthome.control.title': 'Unified Control, Effortless Routine',
    'smarthome.control.desc': 'Lights, blinds, music, appliances — everything choreographed through a single dashboard or a simple "Good night" voice cue.',
    'smarthome.leap': 'Make the leap from connected devices to a truly intelligent lifestyle.',
    'smarthome.explore': 'Explore our bundles or book a live demo today and see how Smart Living turns houses into responsive, caring partners — 24/7.',
    
    // Industry Taglines
    'industry.hospitality.tagline': 'From check-in to check-out, pure wow.',
    'industry.manufacturing.tagline': 'Machines that fix themselves before they fail.',
    'industry.healthcare.tagline': 'Sharper diagnoses, happier patients.',
    'industry.finance.tagline': 'Secure transactions, intelligent insights.',
    'industry.retail.tagline': 'Personalized shopping, automated inventory.',
    'industry.smart.tagline': 'Your home, thinking ahead for you.',
    
    // Industry Status
    'industry.finance.status': 'Coming Soon',
    'industry.retail.status': 'Coming Soon',
    
    // Sections
    'section.transforming': 'Transforming Businesses Worldwide',
    'section.method': 'The EA Method',
    'section.why': 'Why Choose EA Solutions?',
    'section.clients': 'Our Clients',
    'section.testimonials': 'Client Testimonials',
    'section.contact': 'Get in Touch',
    
    // Footer
    'footer.description': 'We architect bespoke AI infrastructures that eradicate repetitive work, amplify human potential, and unlock unprecedented levels of efficiency.',
    'footer.cta': 'Book Your AI Strategy Call',
    'footer.quickLinks': 'Quick Links',
    'footer.contactInfo': 'Contact Information',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    
    // Legal Pages
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.subtitle': 'How we protect and handle your data',
    'legal.privacy.security': 'Data Security',
    'legal.privacy.security.desc': 'Enterprise-grade protection',
    'legal.privacy.transparency': 'Full Transparency',
    'legal.privacy.transparency.desc': 'Clear data usage policies',
    'legal.privacy.rights': 'Your Rights',
    'legal.privacy.rights.desc': 'Control over your information',
    'legal.privacy.section1.title': 'Data Collection',
    'legal.privacy.section1.content': 'We collect only the information necessary to provide our services. This includes contact details, usage data, and information you choose to share with us.',
    'legal.privacy.section2.title': 'How We Use Your Data',
    'legal.privacy.section2.content': 'Your data helps us improve our services, provide support, and communicate with you about updates and new features. We never sell your personal information to third parties.',
    'legal.privacy.section3.title': 'Your Choices',
    'legal.privacy.section3.content': 'You have the right to access, correct, or delete your personal data at any time. You can also opt out of marketing communications.',
    'legal.privacy.contact.title': 'Privacy Contact',
    'legal.privacy.contact.content': 'If you have questions about our privacy practices, please contact us at:',
    
    'legal.impressum.title': 'Legal Notice',
    'legal.impressum.subtitle': 'Information according to legal requirements',
    'legal.impressum.company.title': 'Company Information',
    'legal.impressum.company.details': 'Company Details',
    'legal.impressum.contact.title': 'Contact Information',
    'legal.impressum.legal.title': 'Legal Information',
    'legal.impressum.legal.responsibility': 'Content Responsibility',
    'legal.impressum.legal.responsibility.content': 'Responsible for the content of this website is EA Solutions, represented by Ali H.',
    'legal.impressum.legal.liability': 'Liability for Content',
    'legal.impressum.legal.liability.content': 'We make every effort to keep the information on our website current, but accept no liability for the content. Visitors use the content at their own risk.',
    'legal.impressum.legal.copyright': 'Copyright',
    'legal.impressum.legal.copyright.content': 'The content and works provided on these pages are governed by German copyright law. Duplication, processing, distribution, or any form of commercialization of such material beyond the scope of the copyright law shall require the prior written consent of its respective author or creator.',
    'legal.impressum.dispute.title': 'Dispute Resolution',
    'legal.impressum.dispute.content': 'The European Commission provides a platform for online dispute resolution (OS): https://ec.europa.eu/consumers/odr. We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.',
    
    // Common Terms
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.bookCall': 'Book Your Call',
    'common.visitWebsite': 'Visit Website',
    'common.backToHome': 'Back to Home',
    'common.viewAll': 'View All',
    'common.exploreMore': 'Explore More',
    'common.getQuote': 'Get Quote',
    'common.schedule': 'Schedule',
    'common.download': 'Download',
    'common.contact': 'Contact',
    'common.demo': 'Demo',
    'common.portfolio': 'Portfolio',
    'common.consultation': 'Consultation',
    'common.support': 'Support',
    'common.features': 'Features',
    'common.pricing': 'Pricing',
    'common.testimonials': 'Testimonials',
    'common.process': 'Process',
    'common.results': 'Results',
    'common.benefits': 'Benefits',
    'common.solutions': 'Solutions',
    'common.services': 'Services',
    'common.products': 'Products',
    'common.clients': 'Clients',
    'common.projects': 'Projects',
    'common.success': 'Success',
    'common.transformation': 'Transformation',
    'common.innovation': 'Innovation',
    'common.technology': 'Technology',
    'common.intelligence': 'Intelligence',
    'common.automation': 'Automation',
    'common.optimization': 'Optimization',
    'common.efficiency': 'Efficiency',
    'common.performance': 'Performance',
    'common.security': 'Security',
    'common.compliance': 'Compliance',
    'common.integration': 'Integration',
    'common.scalability': 'Scalability',
    'common.reliability': 'Reliability',
    'common.quality': 'Quality',
    'common.excellence': 'Excellence',
    'common.expertise': 'Expertise',
    'common.experience': 'Experience',
    'common.knowledge': 'Knowledge',
    'common.strategy': 'Strategy',
    'common.implementation': 'Implementation',
    'common.deployment': 'Deployment',
    'common.maintenance': 'Maintenance',
    'common.monitoring': 'Monitoring',
    'common.analytics': 'Analytics',
    'common.insights': 'Insights',
    'common.reporting': 'Reporting',
    'common.dashboard': 'Dashboard',
    'common.interface': 'Interface',
    'common.platform': 'Platform',
    'common.system': 'System',
    'common.framework': 'Framework',
    'common.architecture': 'Architecture',
    'common.infrastructure': 'Infrastructure',
    'common.network': 'Network',
    'common.database': 'Database',
    'common.storage': 'Storage',
    'common.backup': 'Backup',
    'common.recovery': 'Recovery',
    'common.availability': 'Availability',
    'common.uptime': 'Uptime',
    'common.performance': 'Performance',
    'common.speed': 'Speed',
    'common.response': 'Response',
    'common.latency': 'Latency',
    'common.throughput': 'Throughput',
    'common.capacity': 'Capacity',
    'common.load': 'Load',
    'common.traffic': 'Traffic',
    'common.users': 'Users',
    'common.sessions': 'Sessions',
    'common.requests': 'Requests',
    'common.transactions': 'Transactions',
    'common.operations': 'Operations',
    'common.processes': 'Processes',
    'common.workflows': 'Workflows',
    'common.tasks': 'Tasks',
    'common.activities': 'Activities',
    'common.events': 'Events',
    'common.notifications': 'Notifications',
    'common.alerts': 'Alerts',
    'common.warnings': 'Warnings',
    'common.errors': 'Errors',
    'common.logs': 'Logs',
    'common.audit': 'Audit',
    'common.tracking': 'Tracking',
    'common.monitoring': 'Monitoring',
    'common.surveillance': 'Surveillance',
    'common.detection': 'Detection',
    'common.prevention': 'Prevention',
    'common.protection': 'Protection',
    'common.defense': 'Defense',
    'common.firewall': 'Firewall',
    'common.encryption': 'Encryption',
    'common.authentication': 'Authentication',
    'common.authorization': 'Authorization',
    'common.access': 'Access',
    'common.permissions': 'Permissions',
    'common.roles': 'Roles',
    'common.privileges': 'Privileges',
    'common.rights': 'Rights',
    'common.policies': 'Policies',
    'common.rules': 'Rules',
    'common.regulations': 'Regulations',
    'common.standards': 'Standards',
    'common.guidelines': 'Guidelines',
    'common.procedures': 'Procedures',
    'common.protocols': 'Protocols',
    'common.methods': 'Methods',
    'common.techniques': 'Techniques',
    'common.approaches': 'Approaches',
    'common.practices': 'Practices',
    'common.principles': 'Principles',
    'common.concepts': 'Concepts',
    'common.theories': 'Theories',
    'common.models': 'Models',
    'common.algorithms': 'Algorithms',
    'common.calculations': 'Calculations',
    'common.computations': 'Computations',
    'common.processing': 'Processing',
    'common.analysis': 'Analysis',
    'common.evaluation': 'Evaluation',
    'common.assessment': 'Assessment',
    'common.measurement': 'Measurement',
    'common.metrics': 'Metrics',
    'common.indicators': 'Indicators',
    'common.statistics': 'Statistics',
    'common.data': 'Data',
    'common.information': 'Information',
    'common.content': 'Content',
    'common.resources': 'Resources',
    'common.assets': 'Assets',
    'common.files': 'Files',
    'common.documents': 'Documents',
    'common.records': 'Records',
    'common.entries': 'Entries',
    'common.items': 'Items',
    'common.elements': 'Elements',
    'common.components': 'Components',
    'common.modules': 'Modules',
    'common.plugins': 'Plugins',
    'common.extensions': 'Extensions',
    'common.addons': 'Add-ons',
    'common.tools': 'Tools',
    'common.utilities': 'Utilities',
    'common.applications': 'Applications',
    'common.software': 'Software',
    'common.programs': 'Programs',
    'common.scripts': 'Scripts',
    'common.code': 'Code',
    'common.development': 'Development',
    'common.programming': 'Programming',
    'common.coding': 'Coding',
    'common.scripting': 'Scripting',
    'common.debugging': 'Debugging',
    'common.testing': 'Testing',
    'common.validation': 'Validation',
    'common.verification': 'Verification',
    'common.certification': 'Certification',
    'common.approval': 'Approval',
    'common.acceptance': 'Acceptance',
    'common.confirmation': 'Confirmation',
    'common.acknowledgment': 'Acknowledgment',
    'common.recognition': 'Recognition',
    'common.identification': 'Identification',
    'common.classification': 'Classification',
    'common.categorization': 'Categorization',
    'common.organization': 'Organization',
    'common.structure': 'Structure',
    'common.hierarchy': 'Hierarchy',
    'common.taxonomy': 'Taxonomy',
    'common.ontology': 'Ontology',
    'common.schema': 'Schema',
    'common.format': 'Format',
    'common.layout': 'Layout',
    'common.design': 'Design',
    'common.style': 'Style',
    'common.theme': 'Theme',
    'common.template': 'Template',
    'common.pattern': 'Pattern',
    'common.model': 'Model',
    'common.prototype': 'Prototype',
    'common.sample': 'Sample',
    'common.example': 'Example',
    'common.instance': 'Instance',
    'common.case': 'Case',
    'common.scenario': 'Scenario',
    'common.situation': 'Situation',
    'common.condition': 'Condition',
    'common.state': 'State',
    'common.status': 'Status',
    'common.position': 'Position',
    'common.location': 'Location',
    'common.place': 'Place',
    'common.site': 'Site',
    'common.area': 'Area',
    'common.region': 'Region',
    'common.zone': 'Zone',
    'common.sector': 'Sector',
    'common.domain': 'Domain',
    'common.field': 'Field',
    'common.scope': 'Scope',
    'common.range': 'Range',
    'common.extent': 'Extent',
    'common.scale': 'Scale',
    'common.size': 'Size',
    'common.dimension': 'Dimension',
    'common.measurement': 'Measurement',
    'common.quantity': 'Quantity',
    'common.amount': 'Amount',
    'common.volume': 'Volume',
    'common.capacity': 'Capacity',
    'common.limit': 'Limit',
    'common.threshold': 'Threshold',
    'common.boundary': 'Boundary',
    'common.border': 'Border',
    'common.edge': 'Edge',
    'common.margin': 'Margin',
    'common.padding': 'Padding',
    'common.spacing': 'Spacing',
    'common.gap': 'Gap',
    'common.distance': 'Distance',
    'common.length': 'Length',
    'common.width': 'Width',
    'common.height': 'Height',
    'common.depth': 'Depth',
    'common.thickness': 'Thickness',
    'common.weight': 'Weight',
    'common.mass': 'Mass',
    'common.density': 'Density',
    'common.pressure': 'Pressure',
    'common.force': 'Force',
    'common.power': 'Power',
    'common.energy': 'Energy',
    'common.voltage': 'Voltage',
    'common.current': 'Current',
    'common.resistance': 'Resistance',
    'common.frequency': 'Frequency',
    'common.amplitude': 'Amplitude',
    'common.wavelength': 'Wavelength',
    'common.signal': 'Signal',
    'common.noise': 'Noise',
    'common.interference': 'Interference',
    'common.distortion': 'Distortion',
    'common.quality': 'Quality',
    'common.clarity': 'Clarity',
    'common.resolution': 'Resolution',
    'common.precision': 'Precision',
    'common.accuracy': 'Accuracy',
    'common.reliability': 'Reliability',
    'common.stability': 'Stability',
    'common.consistency': 'Consistency',
    'common.uniformity': 'Uniformity',
    'common.standardization': 'Standardization',
    'common.normalization': 'Normalization',
    'common.optimization': 'Optimization',
    'common.improvement': 'Improvement',
    'common.enhancement': 'Enhancement',
    'common.upgrade': 'Upgrade',
    'common.update': 'Update',
    'common.revision': 'Revision',
    'common.modification': 'Modification',
    'common.adjustment': 'Adjustment',
    'common.calibration': 'Calibration',
    'common.tuning': 'Tuning',
    'common.configuration': 'Configuration',
    'common.setup': 'Setup',
    'common.installation': 'Installation',
    'common.deployment': 'Deployment',
    'common.launch': 'Launch',
    'common.startup': 'Startup',
    'common.initialization': 'Initialization',
    'common.activation': 'Activation',
    'common.enablement': 'Enablement',
    'common.operation': 'Operation',
    'common.execution': 'Execution',
    'common.performance': 'Performance',
    'common.functionality': 'Functionality',
    'common.capability': 'Capability',
    'common.feature': 'Feature',
    'common.option': 'Option',
    'common.setting': 'Setting',
    'common.parameter': 'Parameter',
    'common.variable': 'Variable',
    'common.constant': 'Constant',
    'common.value': 'Value',
    'common.result': 'Result',
    'common.output': 'Output',
    'common.outcome': 'Outcome',
    'common.achievement': 'Achievement',
    'common.accomplishment': 'Accomplishment',
    'common.success': 'Success',
    'common.failure': 'Failure',
    'common.error': 'Error',
    'common.exception': 'Exception',
    'common.issue': 'Issue',
    'common.problem': 'Problem',
    'common.challenge': 'Challenge',
    'common.difficulty': 'Difficulty',
    'common.obstacle': 'Obstacle',
    'common.barrier': 'Barrier',
    'common.limitation': 'Limitation',
    'common.constraint': 'Constraint',
    'common.restriction': 'Restriction',
    'common.requirement': 'Requirement',
    'common.specification': 'Specification',
    'common.criterion': 'Criterion',
    'common.standard': 'Standard',
    'common.benchmark': 'Benchmark',
    'common.reference': 'Reference',
    'common.baseline': 'Baseline',
    'common.target': 'Target',
    'common.goal': 'Goal',
    'common.objective': 'Objective',
    'common.purpose': 'Purpose',
    'common.intention': 'Intention',
    'common.plan': 'Plan',
    'common.strategy': 'Strategy',
    'common.approach': 'Approach',
    'common.method': 'Method',
    'common.technique': 'Technique',
    'common.procedure': 'Procedure',
    'common.process': 'Process',
    'common.workflow': 'Workflow',
    'common.pipeline': 'Pipeline',
    'common.sequence': 'Sequence',
    'common.order': 'Order',
    'common.arrangement': 'Arrangement',
    'common.organization': 'Organization',
    'common.structure': 'Structure',
    'common.framework': 'Framework',
    'common.architecture': 'Architecture',
    'common.design': 'Design',
    'common.blueprint': 'Blueprint',
    'common.schema': 'Schema',
    'common.diagram': 'Diagram',
    'common.chart': 'Chart',
    'common.graph': 'Graph',
    'common.visualization': 'Visualization',
    'common.representation': 'Representation',
    'common.display': 'Display',
    'common.presentation': 'Presentation',
    'common.demonstration': 'Demonstration',
    'common.exhibition': 'Exhibition',
    'common.showcase': 'Showcase',
    'common.preview': 'Preview',
    'common.overview': 'Overview',
    'common.summary': 'Summary',
    'common.abstract': 'Abstract',
    'common.synopsis': 'Synopsis',
    'common.outline': 'Outline',
    'common.description': 'Description',
    'common.explanation': 'Explanation',
    'common.clarification': 'Clarification',
    'common.interpretation': 'Interpretation',
    'common.translation': 'Translation',
    'common.conversion': 'Conversion',
    'common.transformation': 'Transformation',
    'common.migration': 'Migration',
    'common.transition': 'Transition',
    'common.change': 'Change',
    'common.modification': 'Modification',
    'common.alteration': 'Alteration',
    'common.adjustment': 'Adjustment',
    'common.adaptation': 'Adaptation',
    'common.customization': 'Customization',
    'common.personalization': 'Personalization',
    'common.individualization': 'Individualization',
    'common.specialization': 'Specialization',
    'common.optimization': 'Optimization',
    'common.refinement': 'Refinement',
    'common.improvement': 'Improvement',
    'common.enhancement': 'Enhancement',
    'common.advancement': 'Advancement',
    'common.progress': 'Progress',
    'common.development': 'Development',
    'common.evolution': 'Evolution',
    'common.growth': 'Growth',
    'common.expansion': 'Expansion',
    'common.extension': 'Extension',
    'common.enlargement': 'Enlargement',
    'common.increase': 'Increase',
    'common.increment': 'Increment',
    'common.addition': 'Addition',
    'common.supplement': 'Supplement',
    'common.complement': 'Complement',
    'common.completion': 'Completion',
    'common.fulfillment': 'Fulfillment',
    'common.satisfaction': 'Satisfaction',
    
    // Final CTA
    'final.title': 'Ready to Transform Your Business?',
    'final.subtitle': 'Join industry leaders who have revolutionized their operations with EA Solutions.',
    'final.cta': 'Book Your AI Strategy Call'
  },
  
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.solutions': 'Lösungen',
    'nav.method': 'Die EA-Methode',
    'nav.why': 'Warum EA Solutions?',
    'nav.contact': 'Kontakt',
    'nav.services': 'Dienstleistungen',
    'nav.mind': 'MIND',
    
    // Hero Section
    'hero.title': 'Ihr Unternehmen hat einen Körper. Wir bauen seinen Verstand.',
    'hero.subtitle': 'Wir entwickeln maßgeschneiderte KI-Infrastrukturen, die repetitive Arbeit beseitigen, menschliches Potenzial verstärken und beispiellose Effizienz freisetzen.',
    'cta.book': 'Buchen Sie Ihren KI-Strategieanruf',
    'cta.explore': 'Lösungen erkunden',
    
    // Header
    'header.cta': 'KI-Strategieanruf buchen',
    
    // MIND Product
    'mind.title': 'Die universelle KI-Lösung',
    'mind.description': 'Ein intelligentes System, das sich an jede Branche, jeden Workflow und jede Herausforderung anpasst. MIND ist nicht nur KI – es ist die Evolution der Art und Weise, wie Unternehmen denken, lernen und wachsen.',
    'mind.tagline': 'Ein Gehirn, unendliche Workflows.',
    'mind.trusted': 'Vertraut von 4+ Unternehmen in Deutschland und 1 international',
    'mind.cta.start': 'Starten Sie Ihre KI-Transformation',
    'mind.cta.demo': 'Demo ansehen',
    'mind.cta.title': 'Bereit, den Verstand Ihrer Organisation zu entfesseln?',
    'mind.cta.subtitle': 'Schließen Sie sich der KI-Revolution an. Transformieren Sie Ihr Unternehmen. Entfesseln Sie unbegrenztes Potenzial mit MINDs universeller Intelligenz.',
    'mind.cta.trial': 'Kostenlose Testversion starten',
    'mind.cta.schedule': 'Demo planen',
    
    // MIND Features
    'mind.features.title': 'Warum MIND alles verändert',
    'mind.features.subtitle': 'Im Gegensatz zu herkömmlichen KI-Lösungen, die Sie zur Anpassung zwingen, passt sich MIND mit beispielloser Intelligenz und Flexibilität an Sie an.',
    'mind.features.universal.title': 'Universelle KI-Intelligenz',
    'mind.features.universal.desc': 'Ein KI-System, das sich an jede Branche, jeden Workflow und jede Herausforderung mit beispiellosen Lernfähigkeiten anpasst.',
    'mind.features.fast.title': 'Blitzschnelle Implementierung',
    'mind.features.fast.desc': 'Implementieren Sie in Wochen statt Monaten in Ihrer gesamten Organisation, ohne bestehende Arbeitsabläufe zu stören.',
    'mind.features.security.title': 'Sicherheit auf Unternehmensebene',
    'mind.features.security.desc': 'Verschlüsselung auf militärischem Niveau, Zero-Trust-Architektur und Einhaltung aller wichtigen internationalen Standards.',
    'mind.features.integration.title': 'Nahtlose Integration',
    'mind.features.integration.desc': 'Verbindet sich mit über 1000 bestehenden Tools und Plattformen, mit Möglichkeit zur benutzerdefinierten API-Entwicklung.',
    
    // MIND Architecture
    'mind.architecture.title': 'Fortschrittliche KI-Architektur',
    'mind.architecture.subtitle': 'Aufgebaut auf modernster Technologie mit Zuverlässigkeit auf Unternehmensebene und unendlicher Skalierbarkeit.',
    
    // MIND Industries
    'mind.industries.title': 'Eine Lösung, jede Branche',
    'mind.industries.subtitle': 'MIND konfiguriert sich automatisch für Ihre spezifischen Branchenanforderungen mit spezialisierten Modulen und Optimierungen.',
    
    // MIND Pricing
    'mind.pricing.title': 'Transparente Preisgestaltung',
    'mind.pricing.subtitle': 'Wählen Sie den Plan, der zur Größe und den Ambitionen Ihrer Organisation passt. Alle Pläne beinhalten eine 30-tägige kostenlose Testversion.',
    'mind.pricing.pilot': 'Perfekt für kleine Teams, die KI-Transformation testen',
    'mind.pricing.growth': 'Umfassende KI-Transformation für wachsende Unternehmen',
    'mind.pricing.scale': 'Fortschrittliche KI-Funktionen für skalierende Organisationen',
    'mind.pricing.enterprise': 'Unbegrenzte KI-Leistung mit vollständiger Souveränität',
    'mind.pricing.popular': 'Am beliebtesten',
    'mind.pricing.contact': 'Vertrieb kontaktieren',
    'mind.pricing.trial': 'Kostenlose Testversion starten',
    'mind.pricing.features': 'Alle Pläne beinhalten 30-tägige kostenlose Testversion • Keine Einrichtungsgebühren • Jederzeit kündbar',
    
    // MIND Testimonials
    'mind.testimonials.title': 'Vertraut von Branchenführern',
    'mind.testimonials.subtitle': 'Echte Ergebnisse von echten Kunden, die MIND für ihre KI-Transformation gewählt haben.',
    
    // MIND ROI
    'mind.roi.title': 'Berechnen Sie Ihren ROI',
    'mind.roi.subtitle': 'Sehen Sie, wie viel MIND Ihrer Organisation mit unserem intelligenten ROI-Rechner sparen kann.',
    'mind.roi.employees': 'Anzahl der Mitarbeiter',
    'mind.roi.revenue': 'Jahresumsatz (€)',
    'mind.roi.industry': 'Branche',
    'mind.roi.plan': 'Ausgewählter Plan',
    'mind.roi.monthly': 'Monatliche Nettoeinsparungen',
    'mind.roi.annual': 'Jährliche Nettoeinsparungen',
    'mind.roi.payback': 'Amortisation',
    'mind.roi.benefits': 'Prognostizierte Vorteile',
    'mind.roi.report': 'Detaillierten ROI-Bericht erhalten',
    
    // Services
    'services.title': 'KI-gestützte Websites & Apps',
    'services.subtitle': 'Wir bauen intelligente Websites und Anwendungen mit KI-Integration, intelligenter Automatisierung und modernem Design. 40-60% Kosteneinsparung im Vergleich zu großen Unternehmen.',
    'services.tagline': 'Websites, die denken; Apps, die vorausahnen.',
    'services.development.tagline': 'Einmal programmieren, KI halbiert die Kosten.',
    'services.chatbot.tagline': 'Kundendienst, der nie schläft (und nie sagt: \'Bitte warten\').',
    'services.booking.tagline': 'Ihr Kalender, bereits erledigt.',
    
    // Smart Home
    'smarthome.title': 'Smart Home Lösungen',
    'smarthome.tagline': 'Verwandeln Sie vier Wände in einen lebendigen, fürsorglichen Verbündeten.',
    'smarthome.why.title': 'Warum Hausautomatisierung?',
    'smarthome.why.subtitle': 'Weil das Leben zu kurz für Routinearbeiten ist — lassen Sie Ihr Zuhause das erledigen.',
    'smarthome.errand.title': 'Leben ohne Besorgungen',
    'smarthome.errand.desc': 'Ihre persönliche KI erkennt, wann Lebensmittel oder Haushaltsartikel zur Neige gehen, bestellt sie und plant die Lieferung, während Sie sich auf das Wesentliche konzentrieren.',
    'smarthome.booking.title': 'Sofortige Buchungen & Pläne',
    'smarthome.booking.desc': 'Von Konzerten bis zum Flug-Check-in: Ein Sprachbefehl sichert Tickets, reserviert Tische und aktualisiert Ihren Kalender — keine Apps, keine Warteschlangen, kein Stress.',
    'smarthome.climate.title': 'Perfektes Klima, immer',
    'smarthome.climate.desc': 'Adaptive Sensoren lernen Ihre Komfortmuster und das lokale Wetter kennen und passen Heizung, Kühlung und Luftqualität in Echtzeit an. Sparen Sie bis zu 40% Energie ohne einen Finger zu rühren.',
    'smarthome.security.title': 'Sicherheit auf Schutzschild-Niveau & Brandschutz',
    'smarthome.security.desc': 'KI-gesteuerte Kameras, intelligente Schlösser und Rauch-/CO-Melder erkennen Anomalien in Millisekunden, lösen Alarme aus und können sogar Notdienste rufen — egal ob Sie im Erdgeschoss oder tausende Kilometer entfernt sind.',
    'smarthome.care.title': 'Fürsorge über Distanz',
    'smarthome.care.desc': 'Diskrete Sturzsensoren, Medikamentenerinnerungen und Zwei-Wege-Video-Check-ins halten ältere Eltern sicher und verbunden. Wenn etwas nicht stimmt, wissen Sie und die Notfalldienste es sofort.',
    'smarthome.control.title': 'Einheitliche Steuerung, mühelose Routine',
    'smarthome.control.desc': 'Lichter, Jalousien, Musik, Geräte — alles choreografiert über ein einziges Dashboard oder einen einfachen "Gute Nacht"-Sprachbefehl.',
    'smarthome.leap': 'Machen Sie den Sprung von vernetzten Geräten zu einem wirklich intelligenten Lebensstil.',
    'smarthome.explore': 'Erkunden Sie unsere Pakete oder buchen Sie noch heute eine Live-Demo und sehen Sie, wie Smart Living Häuser in reaktionsschnelle, fürsorgliche Partner verwandelt — rund um die Uhr.',
    
    // Industry Taglines
    'industry.hospitality.tagline': 'Vom Check-in bis zum Check-out, pure Begeisterung.',
    'industry.manufacturing.tagline': 'Maschinen, die sich selbst reparieren, bevor sie ausfallen.',
    'industry.healthcare.tagline': 'Präzisere Diagnosen, glücklichere Patienten.',
    'industry.finance.tagline': 'Sichere Transaktionen, intelligente Einblicke.',
    'industry.retail.tagline': 'Personalisiertes Einkaufen, automatisiertes Inventar.',
    'industry.smart.tagline': 'Ihr Zuhause, das für Sie vorausdenkt.',
    
    // Industry Status
    'industry.finance.status': 'Demnächst',
    'industry.retail.status': 'Demnächst',
    
    // Sections
    'section.transforming': 'Unternehmen weltweit transformieren',
    'section.method': 'Die EA-Methode',
    'section.why': 'Warum EA Solutions wählen?',
    'section.clients': 'Unsere Kunden',
    'section.testimonials': 'Kundenstimmen',
    'section.contact': 'Kontakt aufnehmen',
    
    // Footer
    'footer.description': 'Wir entwickeln maßgeschneiderte KI-Infrastrukturen, die repetitive Arbeit beseitigen, menschliches Potenzial verstärken und beispiellose Effizienzsteigerungen ermöglichen.',
    'footer.cta': 'Buchen Sie Ihren KI-Strategieanruf',
    'footer.quickLinks': 'Schnelllinks',
    'footer.contactInfo': 'Kontaktinformationen',
    'footer.rights': 'Alle Rechte vorbehalten',
    'footer.privacy': 'Datenschutz',
    'footer.legal': 'Impressum',
    
    // Legal Pages
    'legal.privacy.title': 'Datenschutzerklärung',
    'legal.privacy.subtitle': 'Wie wir Ihre Daten schützen und verarbeiten',
    'legal.privacy.security': 'Datensicherheit',
    'legal.privacy.security.desc': 'Schutz auf Unternehmensebene',
    'legal.privacy.transparency': 'Volle Transparenz',
    'legal.privacy.transparency.desc': 'Klare Datennutzungsrichtlinien',
    'legal.privacy.rights': 'Ihre Rechte',
    'legal.privacy.rights.desc': 'Kontrolle über Ihre Informationen',
    'legal.privacy.section1.title': 'Datenerhebung',
    'legal.privacy.section1.content': 'Wir erheben nur die Informationen, die zur Erbringung unserer Dienstleistungen erforderlich sind. Dazu gehören Kontaktdaten, Nutzungsdaten und Informationen, die Sie uns mitteilen möchten.',
    'legal.privacy.section2.title': 'Wie wir Ihre Daten verwenden',
    'legal.privacy.section2.content': 'Ihre Daten helfen uns, unsere Dienstleistungen zu verbessern, Support zu bieten und Sie über Updates und neue Funktionen zu informieren. Wir verkaufen Ihre persönlichen Daten niemals an Dritte.',
    'legal.privacy.section3.title': 'Ihre Wahlmöglichkeiten',
    'legal.privacy.section3.content': 'Sie haben das Recht, jederzeit auf Ihre persönlichen Daten zuzugreifen, sie zu korrigieren oder zu löschen. Sie können sich auch von Marketingkommunikationen abmelden.',
    'legal.privacy.contact.title': 'Datenschutzkontakt',
    'legal.privacy.contact.content': 'Wenn Sie Fragen zu unseren Datenschutzpraktiken haben, kontaktieren Sie uns bitte unter:',
    
    'legal.impressum.title': 'Impressum',
    'legal.impressum.subtitle': 'Informationen gemäß gesetzlichen Anforderungen',
    'legal.impressum.company.title': 'Unternehmensinformationen',
    'legal.impressum.company.details': 'Unternehmensdetails',
    'legal.impressum.contact.title': 'Kontaktinformationen',
    'legal.impressum.legal.title': 'Rechtliche Informationen',
    'legal.impressum.legal.responsibility': 'Inhaltliche Verantwortung',
    'legal.impressum.legal.responsibility.content': 'Verantwortlich für den Inhalt dieser Website ist EA Solutions, vertreten durch Ali H.',
    'legal.impressum.legal.liability': 'Haftung für Inhalte',
    'legal.impressum.legal.liability.content': 'Wir bemühen uns, die Informationen auf unserer Website aktuell zu halten, übernehmen jedoch keine Haftung für die Inhalte. Besucher nutzen die Inhalte auf eigenes Risiko.',
    'legal.impressum.legal.copyright': 'Urheberrecht',
    'legal.impressum.legal.copyright.content': 'Die auf diesen Seiten bereitgestellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.',
    'legal.impressum.dispute.title': 'Streitschlichtung',
    'legal.impressum.dispute.content': 'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr. Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.',
    
    // Common Terms
    'common.learnMore': 'Mehr erfahren',
    'common.getStarted': 'Loslegen',
    'common.bookCall': 'Anruf buchen',
    'common.visitWebsite': 'Website besuchen',
    'common.backToHome': 'Zurück zur Startseite',
    'common.viewAll': 'Alle anzeigen',
    'common.exploreMore': 'Mehr erkunden',
    'common.getQuote': 'Angebot anfordern',
    'common.schedule': 'Termin vereinbaren',
    'common.download': 'Herunterladen',
    'common.contact': 'Kontakt',
    'common.demo': 'Demo',
    'common.portfolio': 'Portfolio',
    'common.consultation': 'Beratung',
    'common.support': 'Support',
    'common.features': 'Funktionen',
    'common.pricing': 'Preise',
    'common.testimonials': 'Kundenstimmen',
    'common.process': 'Prozess',
    'common.results': 'Ergebnisse',
    'common.benefits': 'Vorteile',
    'common.solutions': 'Lösungen',
    'common.services': 'Dienstleistungen',
    'common.products': 'Produkte',
    'common.clients': 'Kunden',
    'common.projects': 'Projekte',
    'common.success': 'Erfolg',
    'common.transformation': 'Transformation',
    'common.innovation': 'Innovation',
    'common.technology': 'Technologie',
    'common.intelligence': 'Intelligenz',
    'common.automation': 'Automatisierung',
    'common.optimization': 'Optimierung',
    'common.efficiency': 'Effizienz',
    'common.performance': 'Leistung',
    'common.security': 'Sicherheit',
    'common.compliance': 'Compliance',
    'common.integration': 'Integration',
    'common.scalability': 'Skalierbarkeit',
    'common.reliability': 'Zuverlässigkeit',
    'common.quality': 'Qualität',
    'common.excellence': 'Exzellenz',
    'common.expertise': 'Expertise',
    'common.experience': 'Erfahrung',
    'common.knowledge': 'Wissen',
    'common.strategy': 'Strategie',
    'common.implementation': 'Implementierung',
    'common.deployment': 'Bereitstellung',
    'common.maintenance': 'Wartung',
    'common.monitoring': 'Überwachung',
    'common.analytics': 'Analytik',
    'common.insights': 'Einblicke',
    'common.reporting': 'Berichterstattung',
    'common.dashboard': 'Dashboard',
    'common.interface': 'Schnittstelle',
    'common.platform': 'Plattform',
    'common.system': 'System',
    'common.framework': 'Framework',
    'common.architecture': 'Architektur',
    'common.infrastructure': 'Infrastruktur',
    'common.network': 'Netzwerk',
    'common.database': 'Datenbank',
    'common.storage': 'Speicher',
    'common.backup': 'Sicherung',
    'common.recovery': 'Wiederherstellung',
    'common.availability': 'Verfügbarkeit',
    'common.uptime': 'Betriebszeit',
    'common.performance': 'Leistung',
    'common.speed': 'Geschwindigkeit',
    'common.response': 'Antwort',
    'common.latency': 'Latenz',
    'common.throughput': 'Durchsatz',
    'common.capacity': 'Kapazität',
    'common.load': 'Last',
    'common.traffic': 'Verkehr',
    'common.users': 'Benutzer',
    'common.sessions': 'Sitzungen',
    'common.requests': 'Anfragen',
    'common.transactions': 'Transaktionen',
    'common.operations': 'Operationen',
    'common.processes': 'Prozesse',
    'common.workflows': 'Arbeitsabläufe',
    'common.tasks': 'Aufgaben',
    'common.activities': 'Aktivitäten',
    'common.events': 'Ereignisse',
    'common.notifications': 'Benachrichtigungen',
    'common.alerts': 'Warnungen',
    'common.warnings': 'Warnhinweise',
    'common.errors': 'Fehler',
    'common.logs': 'Protokolle',
    'common.audit': 'Prüfung',
    'common.tracking': 'Verfolgung',
    'common.monitoring': 'Überwachung',
    'common.surveillance': 'Überwachung',
    'common.detection': 'Erkennung',
    'common.prevention': 'Prävention',
    'common.protection': 'Schutz',
    'common.defense': 'Verteidigung',
    'common.firewall': 'Firewall',
    'common.encryption': 'Verschlüsselung',
    'common.authentication': 'Authentifizierung',
    'common.authorization': 'Autorisierung',
    'common.access': 'Zugriff',
    'common.permissions': 'Berechtigungen',
    'common.roles': 'Rollen',
    'common.privileges': 'Privilegien',
    'common.rights': 'Rechte',
    'common.policies': 'Richtlinien',
    'common.rules': 'Regeln',
    'common.regulations': 'Vorschriften',
    'common.standards': 'Standards',
    'common.guidelines': 'Richtlinien',
    'common.procedures': 'Verfahren',
    'common.protocols': 'Protokolle',
    'common.methods': 'Methoden',
    'common.techniques': 'Techniken',
    'common.approaches': 'Ansätze',
    'common.practices': 'Praktiken',
    'common.principles': 'Prinzipien',
    'common.concepts': 'Konzepte',
    'common.theories': 'Theorien',
    'common.models': 'Modelle',
    'common.algorithms': 'Algorithmen',
    'common.calculations': 'Berechnungen',
    'common.computations': 'Berechnungen',
    'common.processing': 'Verarbeitung',
    'common.analysis': 'Analyse',
    'common.evaluation': 'Auswertung',
    'common.assessment': 'Bewertung',
    'common.measurement': 'Messung',
    'common.metrics': 'Metriken',
    'common.indicators': 'Indikatoren',
    'common.statistics': 'Statistiken',
    'common.data': 'Daten',
    'common.information': 'Informationen',
    'common.content': 'Inhalt',
    'common.resources': 'Ressourcen',
    'common.assets': 'Assets',
    'common.files': 'Dateien',
    'common.documents': 'Dokumente',
    'common.records': 'Aufzeichnungen',
    'common.entries': 'Einträge',
    'common.items': 'Elemente',
    'common.elements': 'Elemente',
    'common.components': 'Komponenten',
    'common.modules': 'Module',
    'common.plugins': 'Plugins',
    'common.extensions': 'Erweiterungen',
    'common.addons': 'Add-ons',
    'common.tools': 'Werkzeuge',
    'common.utilities': 'Dienstprogramme',
    'common.applications': 'Anwendungen',
    'common.software': 'Software',
    'common.programs': 'Programme',
    'common.scripts': 'Skripte',
    'common.code': 'Code',
    'common.development': 'Entwicklung',
    'common.programming': 'Programmierung',
    'common.coding': 'Codierung',
    'common.scripting': 'Skripterstellung',
    'common.debugging': 'Fehlerbehebung',
    'common.testing': 'Testen',
    'common.validation': 'Validierung',
    'common.verification': 'Verifizierung',
    'common.certification': 'Zertifizierung',
    'common.approval': 'Genehmigung',
    'common.acceptance': 'Akzeptanz',
    'common.confirmation': 'Bestätigung',
    'common.acknowledgment': 'Anerkennung',
    'common.recognition': 'Erkennung',
    'common.identification': 'Identifikation',
    'common.classification': 'Klassifizierung',
    'common.categorization': 'Kategorisierung',
    'common.organization': 'Organisation',
    'common.structure': 'Struktur',
    'common.hierarchy': 'Hierarchie',
    'common.taxonomy': 'Taxonomie',
    'common.ontology': 'Ontologie',
    'common.schema': 'Schema',
    'common.format': 'Format',
    'common.layout': 'Layout',
    'common.design': 'Design',
    'common.style': 'Stil',
    'common.theme': 'Thema',
    'common.template': 'Vorlage',
    'common.pattern': 'Muster',
    'common.model': 'Modell',
    'common.prototype': 'Prototyp',
    'common.sample': 'Beispiel',
    'common.example': 'Beispiel',
    'common.instance': 'Instanz',
    'common.case': 'Fall',
    'common.scenario': 'Szenario',
    'common.situation': 'Situation',
    'common.condition': 'Bedingung',
    'common.state': 'Zustand',
    'common.status': 'Status',
    'common.position': 'Position',
    'common.location': 'Standort',
    'common.place': 'Ort',
    'common.site': 'Standort',
    'common.area': 'Bereich',
    'common.region': 'Region',
    'common.zone': 'Zone',
    'common.sector': 'Sektor',
    'common.domain': 'Domäne',
    'common.field': 'Feld',
    'common.scope': 'Umfang',
    'common.range': 'Bereich',
    'common.extent': 'Ausmaß',
    'common.scale': 'Skala',
    'common.size': 'Größe',
    'common.dimension': 'Dimension',
    'common.measurement': 'Messung',
    'common.quantity': 'Menge',
    'common.amount': 'Betrag',
    'common.volume': 'Volumen',
    'common.capacity': 'Kapazität',
    'common.limit': 'Limit',
    'common.threshold': 'Schwellenwert',
    'common.boundary': 'Grenze',
    'common.border': 'Rand',
    'common.edge': 'Kante',
    'common.margin': 'Rand',
    'common.padding': 'Polsterung',
    'common.spacing': 'Abstand',
    'common.gap': 'Lücke',
    'common.distance': 'Distanz',
    'common.length': 'Länge',
    'common.width': 'Breite',
    'common.height': 'Höhe',
    'common.depth': 'Tiefe',
    'common.thickness': 'Dicke',
    'common.weight': 'Gewicht',
    'common.mass': 'Masse',
    'common.density': 'Dichte',
    'common.pressure': 'Druck',
    'common.force': 'Kraft',
    'common.power': 'Leistung',
    'common.energy': 'Energie',
    'common.voltage': 'Spannung',
    'common.current': 'Strom',
    'common.resistance': 'Widerstand',
    'common.frequency': 'Frequenz',
    'common.amplitude': 'Amplitude',
    'common.wavelength': 'Wellenlänge',
    'common.signal': 'Signal',
    'common.noise': 'Rauschen',
    'common.interference': 'Interferenz',
    'common.distortion': 'Verzerrung',
    'common.quality': 'Qualität',
    'common.clarity': 'Klarheit',
    'common.resolution': 'Auflösung',
    'common.precision': 'Präzision',
    'common.accuracy': 'Genauigkeit',
    'common.reliability': 'Zuverlässigkeit',
    'common.stability': 'Stabilität',
    'common.consistency': 'Konsistenz',
    'common.uniformity': 'Einheitlichkeit',
    'common.standardization': 'Standardisierung',
    'common.normalization': 'Normalisierung',
    'common.optimization': 'Optimierung',
    'common.improvement': 'Verbesserung',
    'common.enhancement': 'Verbesserung',
    'common.upgrade': 'Upgrade',
    'common.update': 'Update',
    'common.revision': 'Revision',
    'common.modification': 'Modifikation',
    'common.adjustment': 'Anpassung',
    'common.calibration': 'Kalibrierung',
    'common.tuning': 'Abstimmung',
    'common.configuration': 'Konfiguration',
    'common.setup': 'Einrichtung',
    'common.installation': 'Installation',
    'common.deployment': 'Bereitstellung',
    'common.launch': 'Start',
    'common.startup': 'Inbetriebnahme',
    'common.initialization': 'Initialisierung',
    'common.activation': 'Aktivierung',
    'common.enablement': 'Aktivierung',
    'common.operation': 'Betrieb',
    'common.execution': 'Ausführung',
    'common.performance': 'Leistung',
    'common.functionality': 'Funktionalität',
    'common.capability': 'Fähigkeit',
    'common.feature': 'Funktion',
    'common.option': 'Option',
    'common.setting': 'Einstellung',
    'common.parameter': 'Parameter',
    'common.variable': 'Variable',
    'common.constant': 'Konstante',
    'common.value': 'Wert',
    'common.result': 'Ergebnis',
    'common.output': 'Ausgabe',
    'common.outcome': 'Ergebnis',
    'common.achievement': 'Errungenschaft',
    'common.accomplishment': 'Leistung',
    'common.success': 'Erfolg',
    'common.failure': 'Fehler',
    'common.error': 'Fehler',
    'common.exception': 'Ausnahme',
    'common.issue': 'Problem',
    'common.problem': 'Problem',
    'common.challenge': 'Herausforderung',
    'common.difficulty': 'Schwierigkeit',
    'common.obstacle': 'Hindernis',
    'common.barrier': 'Barriere',
    'common.limitation': 'Einschränkung',
    'common.constraint': 'Einschränkung',
    'common.restriction': 'Beschränkung',
    'common.requirement': 'Anforderung',
    'common.specification': 'Spezifikation',
    'common.criterion': 'Kriterium',
    'common.standard': 'Standard',
    'common.benchmark': 'Benchmark',
    'common.reference': 'Referenz',
    'common.baseline': 'Baseline',
    'common.target': 'Ziel',
    'common.goal': 'Ziel',
    'common.objective': 'Zielsetzung',
    'common.purpose': 'Zweck',
    'common.intention': 'Absicht',
    'common.plan': 'Plan',
    'common.strategy': 'Strategie',
    'common.approach': 'Ansatz',
    'common.method': 'Methode',
    'common.technique': 'Technik',
    'common.procedure': 'Verfahren',
    'common.process': 'Prozess',
    'common.workflow': 'Arbeitsablauf',
    'common.pipeline': 'Pipeline',
    'common.sequence': 'Sequenz',
    'common.order': 'Reihenfolge',
    'common.arrangement': 'Anordnung',
    'common.organization': 'Organisation',
    'common.structure': 'Struktur',
    'common.framework': 'Framework',
    'common.architecture': 'Architektur',
    'common.design': 'Design',
    'common.blueprint': 'Blaupause',
    'common.schema': 'Schema',
    'common.diagram': 'Diagramm',
    'common.chart': 'Diagramm',
    'common.graph': 'Graph',
    'common.visualization': 'Visualisierung',
    'common.representation': 'Darstellung',
    'common.display': 'Anzeige',
    'common.presentation': 'Präsentation',
    'common.demonstration': 'Demonstration',
    'common.exhibition': 'Ausstellung',
    'common.showcase': 'Präsentation',
    'common.preview': 'Vorschau',
    'common.overview': 'Überblick',
    'common.summary': 'Zusammenfassung',
    'common.abstract': 'Abstrakt',
    'common.synopsis': 'Synopsis',
    'common.outline': 'Gliederung',
    'common.description': 'Beschreibung',
    'common.explanation': 'Erklärung',
    'common.clarification': 'Klarstellung',
    'common.interpretation': 'Interpretation',
    'common.translation': 'Übersetzung',
    'common.conversion': 'Umwandlung',
    'common.transformation': 'Transformation',
    'common.migration': 'Migration',
    'common.transition': 'Übergang',
    'common.change': 'Änderung',
    'common.modification': 'Modifikation',
    'common.alteration': 'Veränderung',
    'common.adjustment': 'Anpassung',
    'common.adaptation': 'Anpassung',
    'common.customization': 'Anpassung',
    'common.personalization': 'Personalisierung',
    'common.individualization': 'Individualisierung',
    'common.specialization': 'Spezialisierung',
    'common.optimization': 'Optimierung',
    'common.refinement': 'Verfeinerung',
    'common.improvement': 'Verbesserung',
    'common.enhancement': 'Verbesserung',
    'common.advancement': 'Fortschritt',
    'common.progress': 'Fortschritt',
    'common.development': 'Entwicklung',
    'common.evolution': 'Evolution',
    'common.growth': 'Wachstum',
    'common.expansion': 'Expansion',
    'common.extension': 'Erweiterung',
    'common.enlargement': 'Vergrößerung',
    'common.increase': 'Zunahme',
    'common.increment': 'Inkrement',
    'common.addition': 'Ergänzung',
    'common.supplement': 'Ergänzung',
    'common.complement': 'Ergänzung',
    'common.completion': 'Fertigstellung',
    'common.fulfillment': 'Erfüllung',
    'common.satisfaction': 'Zufriedenheit',
    
    // Final CTA
    'final.title': 'Bereit, Ihr Unternehmen zu transformieren?',
    'final.subtitle': 'Schließen Sie sich Branchenführern an, die ihre Abläufe mit EA Solutions revolutioniert haben.',
    'final.cta': 'Buchen Sie Ihren KI-Strategieanruf'
  },
  
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.solutions': 'الحلول',
    'nav.method': 'منهجية EA',
    'nav.why': 'لماذا EA Solutions؟',
    'nav.contact': 'اتصل بنا',
    'nav.services': 'الخدمات',
    'nav.mind': 'MIND',
    
    // Hero Section
    'hero.title': 'عملك له جسد. نحن نبني عقله.',
    'hero.subtitle': 'نحن نصمم بنية تحتية للذكاء الاصطناعي مخصصة تقضي على العمل المتكرر، وتعزز الإمكانات البشرية، وتطلق العنان لمستويات غير مسبوقة من الكفاءة.',
    'cta.book': 'احجز مكالمة استراتيجية للذكاء الاصطناعي',
    'cta.explore': 'استكشف الحلول',
    
    // Header
    'header.cta': 'احجز مكالمة استراتيجية للذكاء الاصطناعي',
    
    // MIND Product
    'mind.title': 'الحل الشامل للذكاء الاصطناعي',
    'mind.description': 'نظام ذكي واحد يتكيف مع كل صناعة، وكل سير عمل، وكل تحدي. MIND ليس مجرد ذكاء اصطناعي - إنه تطور في طريقة تفكير الشركات وتعلمها ونموها.',
    'mind.tagline': 'عقل واحد، تدفقات عمل لا نهائية.',
    'mind.trusted': 'موثوق به من قبل أكثر من 4 شركات في ألمانيا و1 دوليًا',
    'mind.cta.start': 'ابدأ تحول الذكاء الاصطناعي الخاص بك',
    'mind.cta.demo': 'شاهد العرض التوضيحي',
    'mind.cta.title': 'هل أنت مستعد لإطلاق العنان لعقل مؤسستك؟',
    'mind.cta.subtitle': 'انضم إلى ثورة الذكاء الاصطناعي. حوّل عملك. أطلق العنان لإمكانات غير محدودة مع ذكاء MIND الشامل.',
    'mind.cta.trial': 'ابدأ النسخة التجريبية المجانية',
    'mind.cta.schedule': 'جدولة عرض توضيحي',
    
    // MIND Features
    'mind.features.title': 'لماذا يغير MIND كل شيء',
    'mind.features.subtitle': 'على عكس حلول الذكاء الاصطناعي التقليدية التي تجبرك على التكيف، يتكيف MIND معك بذكاء ومرونة غير مسبوقين.',
    'mind.features.universal.title': 'ذكاء اصطناعي شامل',
    'mind.features.universal.desc': 'نظام ذكاء اصطناعي واحد يتكيف مع أي صناعة، وأي سير عمل، وأي تحدي مع قدرات تعلم غير مسبوقة.',
    'mind.features.fast.title': 'تنفيذ سريع كالبرق',
    'mind.features.fast.desc': 'نشر في جميع أنحاء مؤسستك في أسابيع، وليس شهور، دون أي تعطيل لسير العمل الحالي.',
    'mind.features.security.title': 'أمان على مستوى المؤسسات',
    'mind.features.security.desc': 'تشفير على مستوى عسكري، وهندسة ثقة صفرية، والتوافق مع جميع المعايير الدولية الرئيسية.',
    'mind.features.integration.title': 'تكامل سلس',
    'mind.features.integration.desc': 'يتصل مع أكثر من 1000 أداة ومنصة موجودة بشكل مباشر، مع إمكانية تطوير واجهة برمجة تطبيقات مخصصة.',
    
    // MIND Architecture
    'mind.architecture.title': 'هندسة ذكاء اصطناعي متقدمة',
    'mind.architecture.subtitle': 'مبني على تقنية متطورة مع موثوقية على مستوى المؤسسات وقابلية للتوسع لا نهائية.',
    
    // MIND Industries
    'mind.industries.title': 'حل واحد، كل صناعة',
    'mind.industries.subtitle': 'يقوم MIND تلقائيًا بتكوين نفسه لاحتياجات صناعتك المحددة مع وحدات وتحسينات متخصصة.',
    
    // MIND Pricing
    'mind.pricing.title': 'تسعير شفاف',
    'mind.pricing.subtitle': 'اختر الخطة التي تناسب حجم مؤسستك وطموحاتها. جميع الخطط تشمل نسخة تجريبية مجانية لمدة 30 يومًا.',
    'mind.pricing.pilot': 'مثالي للفرق الصغيرة التي تختبر تحول الذكاء الاصطناعي',
    'mind.pricing.growth': 'تحول شامل للذكاء الاصطناعي للشركات النامية',
    'mind.pricing.scale': 'قدرات ذكاء اصطناعي متقدمة للمؤسسات المتوسعة',
    'mind.pricing.enterprise': 'قوة ذكاء اصطناعي غير محدودة مع سيادة كاملة',
    'mind.pricing.popular': 'الأكثر شعبية',
    'mind.pricing.contact': 'اتصل بالمبيعات',
    'mind.pricing.trial': 'ابدأ النسخة التجريبية المجانية',
    'mind.pricing.features': 'جميع الخطط تشمل نسخة تجريبية مجانية لمدة 30 يومًا • لا رسوم إعداد • إلغاء في أي وقت',
    
    // MIND Testimonials
    'mind.testimonials.title': 'موثوق به من قبل قادة الصناعة',
    'mind.testimonials.subtitle': 'نتائج حقيقية من عملاء حقيقيين اختاروا MIND لتحول الذكاء الاصطناعي الخاص بهم.',
    
    // MIND ROI
    'mind.roi.title': 'احسب عائد الاستثمار الخاص بك',
    'mind.roi.subtitle': 'انظر كم يمكن أن يوفر MIND لمؤسستك مع حاسبة عائد الاستثمار الذكية الخاصة بنا.',
    'mind.roi.employees': 'عدد الموظفين',
    'mind.roi.revenue': 'الإيرادات السنوية (€)',
    'mind.roi.industry': 'الصناعة',
    'mind.roi.plan': 'الخطة المختارة',
    'mind.roi.monthly': 'صافي التوفير الشهري',
    'mind.roi.annual': 'صافي التوفير السنوي',
    'mind.roi.payback': 'فترة الاسترداد',
    'mind.roi.benefits': 'الفوائد المتوقعة',
    'mind.roi.report': 'احصل على تقرير مفصل لعائد الاستثمار',
    
    // Services
    'services.title': 'مواقع وتطبيقات مدعومة بالذكاء الاصطناعي',
    'services.subtitle': 'نبني مواقع وتطبيقات ذكية مع تكامل الذكاء الاصطناعي، والأتمتة الذكية، والتصميم الحديث. توفير 40-60% في التكاليف مقارنة بالشركات الكبيرة.',
    'services.tagline': 'مواقع تفكر؛ تطبيقات تتوقع.',
    'services.development.tagline': 'برمجة مرة واحدة، دع الذكاء الاصطناعي يخفض التكلفة إلى النصف.',
    'services.chatbot.tagline': 'خدمة عملاء لا تنام أبدًا (ولا تقول أبدًا، \'الرجاء الانتظار\').',
    'services.booking.tagline': 'تقويمك، تم التعامل معه بالفعل.',
    
    // Smart Home
    'smarthome.title': 'حلول المنزل الذكي',
    'smarthome.tagline': 'حول أربعة جدران إلى حليف حي ومهتم.',
    'smarthome.why.title': 'لماذا أتمتة المنزل؟',
    'smarthome.why.subtitle': 'لأن الحياة قصيرة جدًا للأعمال الروتينية — دع منزلك يتعامل معها.',
    'smarthome.errand.title': 'حياة خالية من المهام',
    'smarthome.errand.desc': 'يتنبأ الذكاء الاصطناعي الشخصي الخاص بك عندما تنخفض مستويات البقالة أو المستلزمات المنزلية، ويقوم بطلبها وجدولة التسليم بينما تركز أنت على ما يهم.',
    'smarthome.booking.title': 'حجوزات وخطط فورية',
    'smarthome.booking.desc': 'من الحفلات الموسيقية إلى تسجيل الوصول للرحلات، أمر صوتي واحد يؤمن التذاكر، ويحجز الطاولات، ويحدث تقويمك — بدون تطبيقات، بدون طوابير، بدون توتر.',
    'smarthome.climate.title': 'مناخ مثالي، دائمًا',
    'smarthome.climate.desc': 'تتعلم المستشعرات التكيفية أنماط راحتك والطقس المحلي، وتضبط التدفئة والتبريد وجودة الهواء في الوقت الفعلي. وفر ما يصل إلى 40% من الطاقة دون رفع إصبع.',
    'smarthome.security.title': 'أمان على مستوى الدرع وحماية من الحرائق',
    'smarthome.security.desc': 'تكتشف الكاميرات المدعومة بالذكاء الاصطناعي، والأقفال الذكية، وكاشفات الدخان/أول أكسيد الكربون الشذوذ في جزء من الثانية، وتطلق التنبيهات، ويمكنها حتى الاتصال بخدمات الطوارئ — سواء كنت في الطابق السفلي أو على بعد آلاف الأميال.',
    'smarthome.care.title': 'رعاية تتجاوز المسافة',
    'smarthome.care.desc': 'تحافظ مستشعرات السقوط المنفصلة، وتذكيرات الأدوية، وفحوصات الفيديو ثنائية الاتجاه على سلامة الوالدين المسنين واتصالهم. إذا كان هناك خطأ ما، فأنت وخدمات الطوارئ تعرفون على الفور.',
    'smarthome.control.title': 'تحكم موحد، روتين سهل',
    'smarthome.control.desc': 'الأضواء، والستائر، والموسيقى، والأجهزة — كل شيء منسق من خلال لوحة تحكم واحدة أو أمر صوتي بسيط "ليلة سعيدة".',
    'smarthome.leap': 'انتقل من الأجهزة المتصلة إلى نمط حياة ذكي حقًا.',
    'smarthome.explore': 'استكشف حزمنا أو احجز عرضًا توضيحيًا مباشرًا اليوم وشاهد كيف يحول Smart Living المنازل إلى شركاء متجاوبين ومهتمين — على مدار الساعة.',
    
    // Industry Taglines
    'industry.hospitality.tagline': 'من تسجيل الوصول إلى المغادرة، إبهار خالص.',
    'industry.manufacturing.tagline': 'آلات تصلح نفسها قبل أن تفشل.',
    'industry.healthcare.tagline': 'تشخيصات أكثر دقة، مرضى أكثر سعادة.',
    'industry.finance.tagline': 'معاملات آمنة، رؤى ذكية.',
    'industry.retail.tagline': 'تسوق مخصص، مخزون آلي.',
    'industry.smart.tagline': 'منزلك، يفكر مسبقًا من أجلك.',
    
    // Industry Status
    'industry.finance.status': 'قريبًا',
    'industry.retail.status': 'قريبًا',
    
    // Sections
    'section.transforming': 'تحويل الأعمال في جميع أنحاء العالم',
    'section.method': 'منهجية EA',
    'section.why': 'لماذا تختار EA Solutions؟',
    'section.clients': 'عملاؤنا',
    'section.testimonials': 'شهادات العملاء',
    'section.contact': 'تواصل معنا',
    
    // Footer
    'footer.description': 'نحن نصمم بنية تحتية للذكاء الاصطناعي مخصصة تقضي على العمل المتكرر، وتعزز الإمكانات البشرية، وتطلق العنان لمستويات غير مسبوقة من الكفاءة.',
    'footer.cta': 'احجز مكالمة استراتيجية للذكاء الاصطناعي',
    'footer.quickLinks': 'روابط سريعة',
    'footer.contactInfo': 'معلومات الاتصال',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.legal': 'إشعار قانوني',
    
    // Legal Pages
    'legal.privacy.title': 'سياسة الخصوصية',
    'legal.privacy.subtitle': 'كيف نحمي ونتعامل مع بياناتك',
    'legal.privacy.security': 'أمن البيانات',
    'legal.privacy.security.desc': 'حماية على مستوى المؤسسات',
    'legal.privacy.transparency': 'شفافية كاملة',
    'legal.privacy.transparency.desc': 'سياسات واضحة لاستخدام البيانات',
    'legal.privacy.rights': 'حقوقك',
    'legal.privacy.rights.desc': 'تحكم في معلوماتك',
    'legal.privacy.section1.title': 'جمع البيانات',
    'legal.privacy.section1.content': 'نجمع فقط المعلومات الضرورية لتقديم خدماتنا. وهذا يشمل تفاصيل الاتصال، وبيانات الاستخدام، والمعلومات التي تختار مشاركتها معنا.',
    'legal.privacy.section2.title': 'كيف نستخدم بياناتك',
    'legal.privacy.section2.content': 'تساعدنا بياناتك في تحسين خدماتنا، وتقديم الدعم، والتواصل معك بشأن التحديثات والميزات الجديدة. نحن لا نبيع معلوماتك الشخصية أبدًا لأطراف ثالثة.',
    'legal.privacy.section3.title': 'خياراتك',
    'legal.privacy.section3.content': 'لديك الحق في الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها في أي وقت. يمكنك أيضًا إلغاء الاشتراك من اتصالات التسويق.',
    'legal.privacy.contact.title': 'جهة اتصال الخصوصية',
    'legal.privacy.contact.content': 'إذا كانت لديك أسئلة حول ممارسات الخصوصية لدينا، يرجى الاتصال بنا على:',
    
    'legal.impressum.title': 'إشعار قانوني',
    'legal.impressum.subtitle': 'معلومات وفقًا للمتطلبات القانونية',
    'legal.impressum.company.title': 'معلومات الشركة',
    'legal.impressum.company.details': 'تفاصيل الشركة',
    'legal.impressum.contact.title': 'معلومات الاتصال',
    'legal.impressum.legal.title': 'المعلومات القانونية',
    'legal.impressum.legal.responsibility': 'مسؤولية المحتوى',
    'legal.impressum.legal.responsibility.content': 'المسؤول عن محتوى هذا الموقع هو EA Solutions، ممثلة بواسطة علي ح.',
    'legal.impressum.legal.liability': 'المسؤولية عن المحتوى',
    'legal.impressum.legal.liability.content': 'نبذل كل جهد للحفاظ على المعلومات على موقعنا محدثة، ولكننا لا نتحمل أي مسؤولية عن المحتوى. يستخدم الزوار المحتوى على مسؤوليتهم الخاصة.',
    'legal.impressum.legal.copyright': 'حقوق النشر',
    'legal.impressum.legal.copyright.content': 'المحتوى والأعمال المقدمة في هذه الصفحات تخضع لقانون حقوق النشر الألماني. يتطلب نسخ أو معالجة أو توزيع أو أي شكل من أشكال التسويق التجاري لهذه المواد خارج نطاق قانون حقوق النشر موافقة خطية مسبقة من مؤلفها أو منشئها.',
    'legal.impressum.dispute.title': 'تسوية المنازعات',
    'legal.impressum.dispute.content': 'توفر المفوضية الأوروبية منصة لتسوية المنازعات عبر الإنترنت (OS): https://ec.europa.eu/consumers/odr. نحن غير راغبين أو ملزمين بالمشاركة في إجراءات تسوية المنازعات أمام مجلس تحكيم المستهلك.',
    
    // Common Terms
    'common.learnMore': 'اعرف المزيد',
    'common.getStarted': 'ابدأ الآن',
    'common.bookCall': 'احجز مكالمتك',
    'common.visitWebsite': 'زيارة الموقع',
    'common.backToHome': 'العودة إلى الرئيسية',
    'common.viewAll': 'عرض الكل',
    'common.exploreMore': 'استكشاف المزيد',
    'common.getQuote': 'احصل على عرض سعر',
    'common.schedule': 'جدولة',
    'common.download': 'تنزيل',
    'common.contact': 'اتصال',
    'common.demo': 'عرض توضيحي',
    'common.portfolio': 'معرض الأعمال',
    'common.consultation': 'استشارة',
    'common.support': 'دعم',
    'common.features': 'ميزات',
    'common.pricing': 'التسعير',
    'common.testimonials': 'شهادات',
    'common.process': 'العملية',
    'common.results': 'النتائج',
    'common.benefits': 'الفوائد',
    'common.solutions': 'الحلول',
    'common.services': 'الخدمات',
    'common.products': 'المنتجات',
    'common.clients': 'العملاء',
    'common.projects': 'المشاريع',
    'common.success': 'النجاح',
    'common.transformation': 'التحول',
    'common.innovation': 'الابتكار',
    'common.technology': 'التكنولوجيا',
    'common.intelligence': 'الذكاء',
    'common.automation': 'الأتمتة',
    'common.optimization': 'التحسين',
    'common.efficiency': 'الكفاءة',
    'common.performance': 'الأداء',
    'common.security': 'الأمان',
    'common.compliance': 'الامتثال',
    'common.integration': 'التكامل',
    'common.scalability': 'قابلية التوسع',
    'common.reliability': 'الموثوقية',
    'common.quality': 'الجودة',
    'common.excellence': 'التميز',
    'common.expertise': 'الخبرة',
    'common.experience': 'التجربة',
    'common.knowledge': 'المعرفة',
    'common.strategy': 'الاستراتيجية',
    'common.implementation': 'التنفيذ',
    'common.deployment': 'النشر',
    'common.maintenance': 'الصيانة',
    'common.monitoring': 'المراقبة',
    'common.analytics': 'التحليلات',
    'common.insights': 'الرؤى',
    'common.reporting': 'التقارير',
    'common.dashboard': 'لوحة المعلومات',
    'common.interface': 'الواجهة',
    'common.platform': 'المنصة',
    'common.system': 'النظام',
    'common.framework': 'الإطار',
    'common.architecture': 'الهندسة',
    'common.infrastructure': 'البنية التحتية',
    'common.network': 'الشبكة',
    'common.database': 'قاعدة البيانات',
    'common.storage': 'التخزين',
    'common.backup': 'النسخ الاحتياطي',
    'common.recovery': 'الاسترداد',
    'common.availability': 'التوفر',
    'common.uptime': 'وقت التشغيل',
    'common.performance': 'الأداء',
    'common.speed': 'السرعة',
    'common.response': 'الاستجابة',
    'common.latency': 'زمن الاستجابة',
    'common.throughput': 'الإنتاجية',
    'common.capacity': 'السعة',
    'common.load': 'الحمل',
    'common.traffic': 'حركة المرور',
    'common.users': 'المستخدمون',
    'common.sessions': 'الجلسات',
    'common.requests': 'الطلبات',
    'common.transactions': 'المعاملات',
    'common.operations': 'العمليات',
    'common.processes': 'العمليات',
    'common.workflows': 'سير العمل',
    'common.tasks': 'المهام',
    'common.activities': 'الأنشطة',
    'common.events': 'الأحداث',
    'common.notifications': 'الإشعارات',
    'common.alerts': 'التنبيهات',
    'common.warnings': 'التحذيرات',
    'common.errors': 'الأخطاء',
    'common.logs': 'السجلات',
    'common.audit': 'التدقيق',
    'common.tracking': 'التتبع',
    'common.monitoring': 'المراقبة',
    'common.surveillance': 'المراقبة',
    'common.detection': 'الكشف',
    'common.prevention': 'الوقاية',
    'common.protection': 'الحماية',
    'common.defense': 'الدفاع',
    'common.firewall': 'جدار الحماية',
    'common.encryption': 'التشفير',
    'common.authentication': 'المصادقة',
    'common.authorization': 'التفويض',
    'common.access': 'الوصول',
    'common.permissions': 'الأذونات',
    'common.roles': 'الأدوار',
    'common.privileges': 'الامتيازات',
    'common.rights': 'الحقوق',
    'common.policies': 'السياسات',
    'common.rules': 'القواعد',
    'common.regulations': 'اللوائح',
    'common.standards': 'المعايير',
    'common.guidelines': 'الإرشادات',
    'common.procedures': 'الإجراءات',
    'common.protocols': 'البروتوكولات',
    'common.methods': 'الطرق',
    'common.techniques': 'التقنيات',
    'common.approaches': 'النهج',
    'common.practices': 'الممارسات',
    'common.principles': 'المبادئ',
    'common.concepts': 'المفاهيم',
    'common.theories': 'النظريات',
    'common.models': 'النماذج',
    'common.algorithms': 'الخوارزميات',
    'common.calculations': 'الحسابات',
    'common.computations': 'الحسابات',
    'common.processing': 'المعالجة',
    'common.analysis': 'التحليل',
    'common.evaluation': 'التقييم',
    'common.assessment': 'التقييم',
    'common.measurement': 'القياس',
    'common.metrics': 'المقاييس',
    'common.indicators': 'المؤشرات',
    'common.statistics': 'الإحصائيات',
    'common.data': 'البيانات',
    'common.information': 'المعلومات',
    'common.content': 'المحتوى',
    'common.resources': 'الموارد',
    'common.assets': 'الأصول',
    'common.files': 'الملفات',
    'common.documents': 'المستندات',
    'common.records': 'السجلات',
    'common.entries': 'الإدخالات',
    'common.items': 'العناصر',
    'common.elements': 'العناصر',
    'common.components': 'المكونات',
    'common.modules': 'الوحدات',
    'common.plugins': 'الإضافات',
    'common.extensions': 'الامتدادات',
    'common.addons': 'الإضافات',
    'common.tools': 'الأدوات',
    'common.utilities': 'المرافق',
    'common.applications': 'التطبيقات',
    'common.software': 'البرمجيات',
    'common.programs': 'البرامج',
    'common.scripts': 'النصوص',
    'common.code': 'الكود',
    'common.development': 'التطوير',
    'common.programming': 'البرمجة',
    'common.coding': 'الترميز',
    'common.scripting': 'البرمجة النصية',
    'common.debugging': 'تصحيح الأخطاء',
    'common.testing': 'الاختبار',
    'common.validation': 'التحقق',
    'common.verification': 'التحقق',
    'common.certification': 'الشهادة',
    'common.approval': 'الموافقة',
    'common.acceptance': 'القبول',
    'common.confirmation': 'التأكيد',
    'common.acknowledgment': 'الإقرار',
    'common.recognition': 'التعرف',
    'common.identification': 'التعريف',
    'common.classification': 'التصنيف',
    'common.categorization': 'التصنيف',
    'common.organization': 'التنظيم',
    'common.structure': 'الهيكل',
    'common.hierarchy': 'التسلسل الهرمي',
    'common.taxonomy': 'التصنيف',
    'common.ontology': 'علم الوجود',
    'common.schema': 'المخطط',
    'common.format': 'التنسيق',
    'common.layout': 'التخطيط',
    'common.design': 'التصميم',
    'common.style': 'النمط',
    'common.theme': 'السمة',
    'common.template': 'القالب',
    'common.pattern': 'النمط',
    'common.model': 'النموذج',
    'common.prototype': 'النموذج الأولي',
    'common.sample': 'العينة',
    'common.example': 'المثال',
    'common.instance': 'المثيل',
    'common.case': 'الحالة',
    'common.scenario': 'السيناريو',
    'common.situation': 'الموقف',
    'common.condition': 'الحالة',
    'common.state': 'الحالة',
    'common.status': 'الحالة',
    'common.position': 'الموضع',
    'common.location': 'الموقع',
    'common.place': 'المكان',
    'common.site': 'الموقع',
    'common.area': 'المنطقة',
    'common.region': 'المنطقة',
    'common.zone': 'المنطقة',
    'common.sector': 'القطاع',
    'common.domain': 'المجال',
    'common.field': 'المجال',
    'common.scope': 'النطاق',
    'common.range': 'النطاق',
    'common.extent': 'المدى',
    'common.scale': 'المقياس',
    'common.size': 'الحجم',
    'common.dimension': 'البعد',
    'common.measurement': 'القياس',
    'common.quantity': 'الكمية',
    'common.amount': 'المبلغ',
    'common.volume': 'الحجم',
    'common.capacity': 'السعة',
    'common.limit': 'الحد',
    'common.threshold': 'العتبة',
    'common.boundary': 'الحدود',
    'common.border': 'الحدود',
    'common.edge': 'الحافة',
    'common.margin': 'الهامش',
    'common.padding': 'الحشو',
    'common.spacing': 'التباعد',
    'common.gap': 'الفجوة',
    'common.distance': 'المسافة',
    'common.length': 'الطول',
    'common.width': 'العرض',
    'common.height': 'الارتفاع',
    'common.depth': 'العمق',
    'common.thickness': 'السماكة',
    'common.weight': 'الوزن',
    'common.mass': 'الكتلة',
    'common.density': 'الكثافة',
    'common.pressure': 'الضغط',
    'common.force': 'القوة',
    'common.power': 'الطاقة',
    'common.energy': 'الطاقة',
    'common.voltage': 'الجهد',
    'common.current': 'التيار',
    'common.resistance': 'المقاومة',
    'common.frequency': 'التردد',
    'common.amplitude': 'السعة',
    'common.wavelength': 'الطول الموجي',
    'common.signal': 'الإشارة',
    'common.noise': 'الضوضاء',
    'common.interference': 'التداخل',
    'common.distortion': 'التشويه',
    'common.quality': 'الجودة',
    'common.clarity': 'الوضوح',
    'common.resolution': 'الدقة',
    'common.precision': 'الدقة',
    'common.accuracy': 'الدقة',
    'common.reliability': 'الموثوقية',
    'common.stability': 'الاستقرار',
    'common.consistency': 'الاتساق',
    'common.uniformity': 'التجانس',
    'common.standardization': 'التوحيد',
    'common.normalization': 'التطبيع',
    'common.optimization': 'التحسين',
    'common.improvement': 'التحسين',
    'common.enhancement': 'التعزيز',
    'common.upgrade': 'الترقية',
    'common.update': 'التحديث',
    'common.revision': 'المراجعة',
    'common.modification': 'التعديل',
    'common.adjustment': 'التعديل',
    'common.calibration': 'المعايرة',
    'common.tuning': 'الضبط',
    'common.configuration': 'التكوين',
    'common.setup': 'الإعداد',
    'common.installation': 'التثبيت',
    'common.deployment': 'النشر',
    'common.launch': 'الإطلاق',
    'common.startup': 'بدء التشغيل',
    'common.initialization': 'التهيئة',
    'common.activation': 'التفعيل',
    'common.enablement': 'التمكين',
    'common.operation': 'التشغيل',
    'common.execution': 'التنفيذ',
    'common.performance': 'الأداء',
    'common.functionality': 'الوظائف',
    'common.capability': 'القدرة',
    'common.feature': 'الميزة',
    'common.option': 'الخيار',
    'common.setting': 'الإعداد',
    'common.parameter': 'المعلمة',
    'common.variable': 'المتغير',
    'common.constant': 'الثابت',
    'common.value': 'القيمة',
    'common.result': 'النتيجة',
    'common.output': 'الإخراج',
    'common.outcome': 'النتيجة',
    'common.achievement': 'الإنجاز',
    'common.accomplishment': 'الإنجاز',
    'common.success': 'النجاح',
    'common.failure': 'الفشل',
    'common.error': 'الخطأ',
    'common.exception': 'الاستثناء',
    'common.issue': 'المشكلة',
    'common.problem': 'المشكلة',
    'common.challenge': 'التحدي',
    'common.difficulty': 'الصعوبة',
    'common.obstacle': 'العقبة',
    'common.barrier': 'الحاجز',
    'common.limitation': 'القيد',
    'common.constraint': 'القيد',
    'common.restriction': 'القيد',
    'common.requirement': 'المتطلب',
    'common.specification': 'المواصفات',
    'common.criterion': 'المعيار',
    'common.standard': 'المعيار',
    'common.benchmark': 'المعيار',
    'common.reference': 'المرجع',
    'common.baseline': 'خط الأساس',
    'common.target': 'الهدف',
    'common.goal': 'الهدف',
    'common.objective': 'الهدف',
    'common.purpose': 'الغرض',
    'common.intention': 'النية',
    'common.plan': 'الخطة',
    'common.strategy': 'الاستراتيجية',
    'common.approach': 'النهج',
    'common.method': 'الطريقة',
    'common.technique': 'التقنية',
    'common.procedure': 'الإجراء',
    'common.process': 'العملية',
    'common.workflow': 'سير العمل',
    'common.pipeline': 'خط الأنابيب',
    'common.sequence': 'التسلسل',
    'common.order': 'الترتيب',
    'common.arrangement': 'الترتيب',
    'common.organization': 'التنظيم',
    'common.structure': 'الهيكل',
    'common.framework': 'الإطار',
    'common.architecture': 'الهندسة',
    'common.design': 'التصميم',
    'common.blueprint': 'المخطط',
    'common.schema': 'المخطط',
    'common.diagram': 'الرسم البياني',
    'common.chart': 'الرسم البياني',
    'common.graph': 'الرسم البياني',
    'common.visualization': 'التصور',
    'common.representation': 'التمثيل',
    'common.display': 'العرض',
    'common.presentation': 'العرض التقديمي',
    'common.demonstration': 'العرض التوضيحي',
    'common.exhibition': 'المعرض',
    'common.showcase': 'العرض',
    'common.preview': 'المعاينة',
    'common.overview': 'نظرة عامة',
    'common.summary': 'ملخص',
    'common.abstract': 'ملخص',
    'common.synopsis': 'موجز',
    'common.outline': 'مخطط',
    'common.description': 'وصف',
    'common.explanation': 'شرح',
    'common.clarification': 'توضيح',
    'common.interpretation': 'تفسير',
    'common.translation': 'ترجمة',
    'common.conversion': 'تحويل',
    'common.transformation': 'تحويل',
    'common.migration': 'ترحيل',
    'common.transition': 'انتقال',
    'common.change': 'تغيير',
    'common.modification': 'تعديل',
    'common.alteration': 'تغيير',
    'common.adjustment': 'تعديل',
    'common.adaptation': 'تكيف',
    'common.customization': 'تخصيص',
    'common.personalization': 'تخصيص',
    'common.individualization': 'تفريد',
    'common.specialization': 'تخصص',
    'common.optimization': 'تحسين',
    'common.refinement': 'تنقيح',
    'common.improvement': 'تحسين',
    'common.enhancement': 'تعزيز',
    'common.advancement': 'تقدم',
    'common.progress': 'تقدم',
    'common.development': 'تطوير',
    'common.evolution': 'تطور',
    'common.growth': 'نمو',
    'common.expansion': 'توسع',
    'common.extension': 'امتداد',
    'common.enlargement': 'توسيع',
    'common.increase': 'زيادة',
    'common.increment': 'زيادة',
    'common.addition': 'إضافة',
    'common.supplement': 'ملحق',
    'common.complement': 'مكمل',
    'common.completion': 'إكمال',
    'common.fulfillment': 'إنجاز',
    'common.satisfaction': 'رضا',
    
    // Final CTA
    'final.title': 'هل أنت مستعد لتحويل عملك؟',
    'final.subtitle': 'انضم إلى قادة الصناعة الذين قاموا بثورة في عملياتهم مع EA Solutions.',
    'final.cta': 'احجز مكالمة استراتيجية للذكاء الاصطناعي'
  }
};

// Define the language context
interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  translate: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Custom hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Language Provider component
interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageSelector: React.FC = () => {
  const { language, setLanguage } = useLanguage();

  return (
    <div className="relative">
      <button
        className="flex items-center space-x-1 p-2 rounded-full bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors duration-300"
        aria-label="Select language"
      >
        <Globe className="h-5 w-5 text-gray-600 dark:text-gray-400" />
        <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
          {languages.find(lang => lang.code === language)?.flag}
        </span>
      </button>
      
      <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 py-2 z-50">
        {languages.map((lang) => (
          <button
            key={lang.code}
            onClick={() => setLanguage(lang.code)}
            className={`w-full text-left px-4 py-2 flex items-center space-x-3 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors ${
              language === lang.code ? 'bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400' : 'text-gray-700 dark:text-gray-300'
            }`}
          >
            <span className="text-xl">{lang.flag}</span>
            <span className="text-sm font-medium">{lang.name}</span>
          </button>
        ))}
      </div>
    </div>
  );
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Try to get the language from localStorage
    const savedLanguage = localStorage.getItem('language');
    // If not found, use browser language or default to English
    if (savedLanguage && languages.some(lang => lang.code === savedLanguage)) {
      return savedLanguage;
    }
    
    const browserLang = navigator.language.split('-')[0];
    return languages.some(lang => lang.code === browserLang) ? browserLang : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const translate = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageSelector;